version: 0.2
phases:
  install:
    runtime-versions:
	nodejs: 12.2 
  pre_build:
    commands:
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm test
      
artifacts:
  files:
    - '**/*'